### ISSUE TITLE
Check Contracts Instead of instanceOf

### ISSUE THREAD

**Issue by iammerrick** [LearnBoost/up#14]
Currently in the up  [executable](https://github.com/LearnBoost/up/blob/master/bin/up#L93-97) on lines 93 - 97 an instanceOf method is employed to detect that the server will honor the appropriate contract. This breaks however when you have a server that honors the http.Server [contract](https://github.com/flatiron/union/blob/master/lib/core.js#L53) but is not an "instance of" http.Server. In this particular case, a union server.

This means anyone using flatiron, or another union project. Will not be able to deploy using up without some hackery. For the time being I can comment out the exception for the particular error check in the up binary and I can use it just fine. 

Would you guys be open to a pull request that checked that the appropriate methods exist instead of using an instanceOf call on http.Server?

**Comment by rauchg** [comment]
Wouldn't you supply a file that exports the result of calling `core.createServer` ?

**Comment by rauchg** [comment]
In other words, the contract is exporting a http server, not exposing the means for constructing a http server.

**Comment by iammerrick** [comment]
I just believe up would be more flexible, in this case with the use of flatiron & union; (the stuff the nodejitsu guys are working on) if it checked for required methods instead of using an instanceOf. This certainly isn't meant as a criticism for either project just a simple idea to allow them to work together nicely. :-). 

In the case of flatiron https://github.com/flatiron/flatiron/blob/master/lib/flatiron/plugins/http.js#L76-85 returns a union server, which deep down seems to be an http.Server and responds to all such methods but is not passing through the instanceOf flag.

**Comment by rauchg** [comment]
But isn't `app.server` in that case an `http.Server` ?

**Comment by rauchg** [comment]
I mean somewhere there needs be a `http.Server` we can forward requests to right ? That's what you can export in your `server.js`, which union I'm sure exports as public API. Unless I'm missing something

**Comment by iammerrick** [comment]
You are right, the app.server is an http.Server. What a fail, haha. Thanks man.

**Comment by rauchg** [comment]
Yep, for anyone else who stumbles upon this trying to run `union` and `up` I just tried this out and it worked fine!

```
 ∞ ~ cd /tmp
 ∞ tmp mkdir iammerrick
 ∞ tmp cd iammerrick/
 ∞ iammerrick npm install union
union@0.1.7 ./node_modules/union 
├── qs@0.3.2
└── pkginfo@0.2.3
 ∞ iammerrick cat > server.js
module.exports = require('union').createServer({
    before: [
        function (req, res) {
          res.writeHead(200);
          res.end('Hello world');
        }
    ]
});

^C
 ∞ iammerrick up server.js 
  up-cli starting cluster with 1 workers on port 3000
  up-cli `kill -s SIGUSR2 28104` or ctrl + r to load new code
  up spawning 1 workers from master 28104
  up worker 28105 created
  up worker 28105 listening on port 55439
```

**Comment by iammerrick** [comment]
Also if you are using flatiron:

``` javascript

var flatiron = require('flatiron'),
    path = require('path'),
    app = flatiron.app;

app.config.file({ file: path.join(__dirname, 'config', 'config.json') });

app.use(flatiron.plugins.http);

app.router.get('/', function () {
  this.res.json({ 'hello': 'world' })
});

app.start();
module.exports = app.server;
```

**Comment by rauchg** [comment]
Excellent, thanks!
