### ISSUE TITLE
X-Forwarded-Proto set to 'httpshttps' (bug in node-http-proxy)

### ISSUE THREAD

**Issue by bkw** [LearnBoost/up#38]
For the record: nodejitsu/node-http-proxy#266 affects distribute, and thus it affects up. The outcome is that behind a reverse proxy that terminates ssl, the header X-Forwarded-Proto is set to "httpshttps", which can give weird results, ie. (express req.protocol).

As soon as nodejitsu releases a fixed package, someone should update distrubute's dependencies and the ones of up.
Or reference a fork in the meantime.

**Comment by bkw** [comment]
sorry, I mistyped the issue number. I meant 266 instead of 226 (now corrected).
Please excuse the confusion.

**Comment by indexzero** [comment]
I'll try to take a look at this over the weekend. There are a couple of bugs I'd like to fix with 0.8 now available.
