### ISSUE TITLE
Pass arguments to the server

### ISSUE THREAD

**Issue by snsparrish** [LearnBoost/up#4]
Any way to pass arguments to the http servers?  I'd like to feed it a config file path, specifically.

**Comment by TooTallNate** [comment]
Not sure about official support, but what about using an environment variable?

**Comment by tj** [comment]
maybe args after `--` should just be fed as argv (haven't looked at what's there yet)

**Comment by snsparrish** [comment]
Environment variable doesn't seem to work.  Maybe I'm just doing it wrong.

**Comment by tj** [comment]
y u do wrong

**Comment by rauchg** [comment]
@visionmedia just fixed `process.env` (see #6)
