### ISSUE TITLE
Not gracefull

### ISSUE THREAD

**Issue by AndreasMadsen** [LearnBoost/up#5]
This module do not restart workers gracefull, it just stop the event loop. Any clients there was about to receive would be destroyed.

A better alternativ is to do `server.close()` and `proces._channel.close()` and perhaps disconnect any clients after an optional timeout.

**Comment by rauchg** [comment]
Have you read the "strategy" section? As a matter of fact, the chance that any requests are aborted is almost null. The only way that that could happen is if a request is taking longer than `workerTimeout`.

**Comment by AndreasMadsen** [comment]
I got that, but I do not see what there prevent the worker from getting new clients 480ms after the 'die' cmd has been send.

I understand the strategy I'm concerned that it is not implemented properly.

**Comment by tj** [comment]
we dont need to close down the channel but we should stop accepting connections

**Comment by tj** [comment]
nvm forgot that we proxy

**Comment by rauchg** [comment]
@AndreasMadsen the whole point of `up` is that we don't need to disconnect clients after a timeout, therefore not dropping any in-flight requests or closing keep-alive sockets.

**Comment by AndreasMadsen** [comment]
@guille I understand that too. What I do not understand is what there prevent the server from accepting new connections 480ms after 'die' cmd is send to the worker. Perhaps you could point to the line of code or explain this in more detail.
