### ISSUE TITLE
Access to process.env

### ISSUE THREAD

**Issue by igm** [LearnBoost/up#6]
Hi, my server.js looks like this:

``` javascript
var http = require('http')
module.exports = http.Server(function (req, res) {
    res.writeHead(200);
    res.end('Hello World');
    console.log(process.env)
});
```

I start it using: `$ up --watch --timeout 500ms server.js`
But what I see in console is just: `{ NODE_CHANNEL_FD: '42' }`

What is the proper way to access process.env ?

**Comment by rauchg** [comment]
Thanks TJ

**Comment by thinkjson** [comment]
Thanks, TJ. This addresses the issue I was having the other day. You rock!
