### ISSUE TITLE
"depreciated" -> what to?

### ISSUE THREAD

**Issue by inspire22** [LearnBoost/up#67]
Is there a better alternative, now that this project has been depreciated?

I'm running a simple node server (faye) and I'd like to have it be able to handle graceful restarts

**Comment by rauchg** [comment]
Nginx—

**Comment by inspire22** [comment]
Is there an nginx module or something? I understand proxying it behind 
nginx, but the service would still need to be restarted - I guess the 
hope would just be that nginx keeps the connections waiting until it is 
back up?

Kevin

Guillermo Rauch wrote:

**Comment by rauchg** [comment]
Alter the config to point to new workers, then send the signal to reload the config. Nginx won't drop a single request and your new code will start handling new requests immediately.
