### ISSUE TITLE
Up and Express?

### ISSUE THREAD

**Issue by snsparrish** [LearnBoost/up#8]
Will 'up' work with 'express'?
I keep getting an error whenever a request is made:
http.js:562
    throw new Error("Can't render headers after they are sent to the client.")

Thanks,
Shawn

**Comment by rauchg** [comment]
**Yes**

``` bash
$ mkdir /tmp/woot
$ cd /tmp/woot
$ npm install express up
$ cat > server.js
```

(paste)

``` js
var app = require('express').createServer();
app.get('/', function (req, res) { res.send('<marquee><h1>hello snsparrish</h1></marquee>'); });
module.exports = app;
```

(press ctrl+c)

``` bash
up server.js
```

![](http://f.cl.ly/items/3f391P310I2M0P2g0n3v/Image%202012.01.31%207:18:50%20PM.png)

**Comment by skylamer** [comment]
Module supplied "_the_file_here.js" does not export a valid `http.Server`.

fix ?

**Comment by rauchg** [comment]
?

**Comment by malkomalko** [comment]
same problems happening for me.. anytime I use the programatic interface and not the cli.

0.6.10 and newest npm...

I'll post a log shortly

**Comment by zmsmith** [comment]
@malkomalko I'm interested in using up from within an express app as well. Haven't written any code yet, but will let you know if I have any success. I know you haven't gotten it working yet, but any gotchas early on I should know about?

Thanks

**Comment by rauchg** [comment]
Did you guys try the example I posted in the comment above?

**Comment by zmsmith** [comment]
It looks like the example above requires you to use the `up` command to start your program. I'm interested in simulating this example:

``` javascript
var up = require('up')
  , master = http.Server().listen(3000)

// initialize up
var srv = up(master, __dirname + '/server');

process.on('SIGUSR2', function () {
  srv.reload();
});
```

**Comment by rauchg** [comment]
Oh. The CLI program uses that API internally so it obviously has to work for that example to work.

**Comment by rauchg** [comment]
In your case, maybe your file is not called `/server` so you have to tweak that.

**Comment by zmsmith** [comment]
I'll check it out, thanks.

**Comment by dbainbridge** [comment]
For Express 3.0x

``` javascript
var express = require('express');
var app = express();
var server = app.listen();

app.get('/', function (req, res) { res.send('<marquee><h1>hello snsparrish</h1></marquee>'); });
module.exports = server;
```

**Comment by jameswyse** [comment]
If anyone comes across the error in the OP:

``` javascript
http.js:562
throw new Error("Can't render headers after they are sent to the client.")
```

It's possibly because you're trying to use your app's http server as the master server. You should create another server for master as all it does is handle proxying to the worker processes.

In my express project I created two files: `server.js` and `up.js`. `server.js` starts (and exports) my express server like above. `up.js` starts the up master server.

``` javascript
var up = require('up'),
    http = require('http');

var options = {
    numWorkers: 2,
    workerTimeout: '500ms',
    assumeReady: true
};

var master = http.Server().listen(4000);
var srv = up(master, __dirname + '/server', options);

process.on('SIGUSR2', function () {
  srv.reload();
});
```
